// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8vOf40gXDikTXSg2nqcVsJtJG5bqkM8',
    appId: '1:855151708999:web:f41aea96b940a6ec625a62',
    messagingSenderId: '855151708999',
    projectId: 'accounts-app-c87ea',
    authDomain: 'accounts-app-c87ea.firebaseapp.com',
    storageBucket: 'accounts-app-c87ea.firebasestorage.app',
    measurementId: 'G-N06YCB3LH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQgB0jDn_GGbmN0WiBhR9wiFkOjd1Y6w',
    appId: '1:855151708999:android:1a30dbd15ff4aeee625a62',
    messagingSenderId: '855151708999',
    projectId: 'accounts-app-c87ea',
    storageBucket: 'accounts-app-c87ea.firebasestorage.app',
  );

}